apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: quakewatch-proj
  namespace: argocd
spec:
  description: Project for QuakeWatch & Monitoring
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
