apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quakewatch
  namespace: argocd
spec:
  project: quakewatch-proj
  source:
    repoURL: https://github.com/Davidvoodo/quakewatch-gitops-monitoring.git
    targetRevision: main
    path: helm/quakewatch
  destination:
    server: https://kubernetes.default.svc
    namespace: quakewatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
