image:
  repository: docker.io/david0mizrahi/quakewatch
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: quakewatch.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  releaseLabel: monitoring
